baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Markus Pad'
theme = 'PaperMod'

[params]
defaultTheme = "auto"

[params.profileMode]
enabled = true
title = "<Title>"
subtitle = "A blog for Markus A.G.A."
imageUrl = "img/me.jpg"
imageTitle = "A sketch of Markus Amano."
imageWidth = 330 # 615 # 1430 # 2860
imageHeight = 475 # 953 # 1907 # 3814 

[[params.profileMode.buttons]]
name = "Blog"
url = "/post"

[[params.profileMode.buttons]]
name = "GitHub"
url = "https://github.com/inokawazu"
