baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Markus Pad'
theme = 'PaperMod'

[markup.goldmark.renderer]
unsafe = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[taxonomies]
tag = 'tags'

[params]
defaultTheme = "auto"
ShowReadingTime = true
ShowToc = true
author = "Markus A.G. Amano"
ShowShareButtons = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true

[params.profileMode]
enabled = true
title = "Markus Pad"
subtitle = """
Welcome to my pad.
I'm your host, Markus Amano, and I so glad you came.
Please check out my humble blog.
CV and professional stuff is below.
About me, I am a assistant professor at NIT Oyama College.
My currently research topic is modeling physics with the holographic principles derived from string theory.
Personally, I enjoy interesting mathematical puzzles and games.
"""
imageUrl = "img/me.jpg"
imageTitle = "Sketch of Markus Amano"
imageWidth = 330 # 615 # 1430 # 2860
imageHeight = 475 # 953 # 1907 # 3814 

[[params.profileMode.buttons]]
name = "Blog"
url = "/post"

[[params.profileMode.buttons]]
name = "iNSPIREHEP"
url = "https://inspirehep.net/authors/1778034?ui-citation-summary=true"

[[params.profileMode.buttons]]
name = "CV"
url = "cv.pdf"

[[params.profileMode.buttons]]
name = "Publications"
url = "publications.pdf"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/inokawazu"

[[params.socialIcons]]
name = "Linkedin"
url = "https://www.linkedin.com/in/markus-amano/"
