baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Markus Pad'
theme = 'PaperMod'

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
defaultTheme = "auto"
ShowReadingTime = true
ShowToc = true
comments = true
disqusShortname = "markus-pad"
author = "Markus A.G. Amano"
ShowShareButtons = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true

[params.profileMode]
enabled = true
title = "<Title>"
subtitle = "A blog for Markus A.G.A."
imageUrl = "img/me.jpg"
imageTitle = "A sketch of Markus Amano."
imageWidth = 330 # 615 # 1430 # 2860
imageHeight = 475 # 953 # 1907 # 3814 

[[params.profileMode.buttons]]
name = "Blog"
url = "/post"

[[params.profileMode.buttons]]
name = "iNSPIREHEP"
url = "https://inspirehep.net/authors/1778034?ui-citation-summary=true"

[[params.profileMode.buttons]]
name = "CV"
url = "cv.pdf"

[[params.profileMode.buttons]]
name = "Publications"
url = "publications.pdf"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/inokawazu"

[[params.socialIcons]]
name = "Linkedin"
url = "https://www.linkedin.com/in/markus-amano/"
